param([Parameter(Mandatory=$true)][string]$Workspace,[Parameter(Mandatory=$true)][string]$OutputPath)
$ErrorActionPreference='Stop';$root=(Resolve-Path -LiteralPath $Workspace).Path;$checks=[Collections.Generic.List[object]]::new();function Add-Check{param([string]$Name,[bool]$Passed,[string]$Detail)$checks.Add([ordered]@{name=$Name;passed=$Passed;detail=$Detail})}
foreach($file in @('index.html','styles.css','script.js')){Add-Check "$file exists" (Test-Path -LiteralPath (Join-Path $root $file) -PathType Leaf) 'Required runnable deliverable.'}
$html=if(Test-Path (Join-Path $root 'index.html')){Get-Content (Join-Path $root 'index.html') -Raw}else{''};$css=if(Test-Path (Join-Path $root 'styles.css')){Get-Content (Join-Path $root 'styles.css') -Raw}else{''};$js=if(Test-Path (Join-Path $root 'script.js')){Get-Content (Join-Path $root 'script.js') -Raw}else{''};$text="$html`n$css`n$js"
foreach($copy in @('Signal Loom','Evidence, woven into decisions.','Capture signal','Export JSON','Import JSON')){Add-Check "required copy: $copy" ($html.Contains($copy)) 'Required product language.'}
foreach($hook in @('signal-list','signal-search','source-filter','theme-filter','status-filter','signal-dialog','signal-detail','toast','import-input')){Add-Check "UI hook: $hook" ($html-match"id=[`"']$hook[`"']") 'Required inspectable behavior hook.'}
Add-Check 'versioned persistence key' ($js-match"signal-loom:v1") 'Required localStorage namespace.';Add-Check 'localStorage used' ($js-match'localStorage\.(getItem|setItem)') 'Data must survive refresh.';Add-Check 'JSON export implemented' ($js-match'Blob\s*\('-and$js-match'URL\.createObjectURL') 'Export must create a downloadable file.';Add-Check 'file import implemented' ($js-match'FileReader|\.text\s*\(') 'Import must read the chosen file.';Add-Check 'schema version validated' ($js-match'schemaVersion') 'Import/export schema must be versioned.';Add-Check 'undo timeout is at least 8s' ($js-match'setTimeout\s*\([^,]+,\s*(8000|[89]\d{3}|\d{5,})') 'Undo window must remain available for at least eight seconds.';Add-Check 'responsive rules present' ($css-match'@media\s*\(') 'Mobile layout is required.';Add-Check 'reduced motion supported' ($css-match'prefers-reduced-motion') 'Motion preference must be respected.';Add-Check 'visible focus styles' ($css-match':focus-visible') 'Keyboard focus must be visible.';Add-Check 'Escape handling present' ($js-match'Escape') 'Dialog and panel should support keyboard dismissal.'
$remote=@([regex]::Matches($text,'(?i)(https?:)?//[^\s"''\)]+')|ForEach-Object{$_.Value}|Where-Object{$_-notmatch'^https?://www\.w3\.org/(2000/svg|1999/xhtml)'}|Select-Object -Unique);Add-Check 'no remote resources' ($remote.Count-eq0) $(if($remote.Count){"Found: $($remote-join', ')"}else{'No remote resources.'})
$passed=@($checks|Where-Object{$_.passed}).Count;$result=[ordered]@{generatedAt=(Get-Date).ToUniversalTime().ToString('o');summary=[ordered]@{passed=$passed;total=$checks.Count};checks=$checks};$parent=Split-Path -Parent $OutputPath;if($parent){New-Item -ItemType Directory -Force -Path $parent|Out-Null};[IO.File]::WriteAllText($OutputPath,($result|ConvertTo-Json -Depth 8),[Text.UTF8Encoding]::new($false));$result|ConvertTo-Json -Depth 8
